a:
  b: "abc"

test: '{cipher}AQAHhbGo+MdxTflPMJCsRwkBpfaPqySOI9OAZddFEIGyeE68wSH4m5YU0nyLCJC5yO1NW0wKHEuFt05sKBpNBddM8Srlqaglhb5ghFcF97+LqlPzVwcexkTyZEZkiHaEWw55OrkkVN0+E+VPJeswAZ38Hzw46g2u7h0wuYX0sd8JPwESJOnOcCPBi29Rd7Tt4etgqHMtA8khfnv7xVpuFwYk6rOJMc/A1KDWoo99Fu1jXxq5XJD4cuU8y+osSarlr+lFOBzW14GNXyGJ3rZ9+DsrtWWmgWynV6dF+i4HYtMGySd/hzwmZ+dZZB+WAMB7JqDA/lrxexklyuw99KXvaMnw0aTXwhr9BoM/yUOCXw0iZX1o0QZobcPUOrYVXlYf958=' 
